internal/commands/scan.go

This was caused by a scan client with the version number Java 15. The code assumed all
client version numbers were going to have a (major.minor) style
and crashed trying to parse the string. The code can now handle
situations where there is a a (major.minor)version number or just a major
version number.

The (scan list) command was throwing an exception. The error was caused

---

internal/commands/root.go
internal/commands/scan.go

Added support for GIT repo scans. To use this include scan type include (--project-source-type "git") and (--repo-url "<your-repo-url>" in a (scan create) call.

Added support for GIT repo scans. To use this include scan type

---

internal/commands/root.go
internal/params/binds.go
internal/params/envs.go
internal/params/keys.go
internal/wrappers/client.go

This brings the CLI arg name inline with the environment variable name for consistency.

Renamed CX_BASE_IAM_URIL to CX_BASE_AUTH_URI.

---

internal/commands/auth.go
internal/commands/root.go
internal/commands/scan.go
internal/commands/utils.go

- (--incremental) should be (--sast-incremental)
- Scan preset is included with all json (scan create) requests. The default is provided as "Checkmarx Default" if it isn't specified with (--sast-preset-name) option.
- Removed (--configure) from (utils) but its still available from the root level
- (Auth register) help was incorrectly show "ast" as the command.
- (--agent) help name says "Scan origin name"
- (--auth-path), has been removed until we hear otherwise.
- The client ID help is now "The oAuth2 client ID"
- The client ID secret help is now "The oAuth2 client secret"
- Moved (completion) option under (utils)

Many small tweaks to CLI parameters:

---

internal/commands/scan.go

- Preset name wasn't allowing for overide.

Preset name wasn't allowing for overide.

---

.circleci/config.yml
internal/commands/root.go
internal/params/binds.go
internal/params/envs.go
internal/params/flags.go
internal/params/keys.go
internal/wrappers/client.go
internal/wrappers/configuration.go

- When authenticating CLI now respects user tenant
- Added environment variable CX_TENANT
- Added global CLI argument (--tenant)
- Added tenant name to (configure) command menu
- Updated version to RC11

CLI now respects user tenant

---

README.md
internal/commands/project.go
internal/commands/root.go
internal/commands/scan.go

- The scan commands (show, delete and cancel) required Scan ID values be passed as an additiona argument. The changes to the help system prevented that argument from being input though. These commands now accept a CLI argument named (--scan-id) to prevent this issue.
- The project commands (show, delete) required Project ID values be passed as an additiona argument. The changes to the help system prevented that argument from being input though. These commands now accept a CLI argument named (--project-id) to prevent this issue.
- Updated documentation to reflect changes to scan and project commands.

Added (--scan-id) and (--project-id) arguments to CLI commands

---

internal/commands/scan.go

- When a scan is created in wait-mode and failed, we are not returning any exit code
Added the step to check the status of the scan and return exit code 1 when the status is not "Completed"

Added step to check the scan status and exit

---

internal/commands/result.go
internal/wrappers/results-json.go
internal/wrappers/results-sarif.go

This PR adds missing fields to the results structure in the CLI.
CweID and QueryID are set as interface{} as different engines return it with different types (string vs int)

Feature/ast 4445/enrich results structure

---

internal/commands/result.go
internal/wrappers/results-json.go
internal/wrappers/results-sarif.go
internal/wrappers/results-summary.go

- rules and results are now parsed in a single loop
- all the result's nodes are added as a location to the result
I'm opening a draft PR so you guys have a look and we can discuss the changes later
Notes:
- a workaround for query id due to AST returning it in different types depending on engine is present
- when the rule id is a CVE, we don't have a friendly name available
- helpUri for each rule is AST docs
- friendly name, when existing, probably won't match PascalCase
https://checkmarx.atlassian.net/browse/AST-5022
Validator used: https://sarifweb.azurewebsites.net/Validation (tick GitHub ingestion rules)

AST-5022 match GitHub validator structure

---

internal/commands/scan.go
internal/params/flags.go
test/integration/scan_test.go

In sequence of the AST-5650 task, the nowait flag was renamed to wait. The default behaviour is waiting for the scan to complete.

Renaming nowait flag to async

---

internal/commands/scan.go
internal/params/flags.go
test/integration/scan_test.go

- Add timeout flag to cancel the scan in minutes
Add timeout mechanism to the CLI that cancels the scan and returns an error code if the timeout is reached.
https://checkmarx.atlassian.net/browse/AST-8492
Added a test that performs a slow scan with a 1 minute timeout and asserts the error and the cancelled state.

AST-8492 Timeout

---

internal/wrappers/configuration/configuration.go

Modified default folder permissions for (cx configure) command to allow proper creation of profile configuration on macs. The permissions were changed from 600 to 700.

Modified default folder permissions for (cx configure) command

---

.github/workflows/ci.yml
internal/commands/auth.go
internal/commands/auth_test.go
internal/wrappers/auth-http.go
test/integration/auth_test.go

Make flag roles required in auth register
- Make flag -r, --roles required
- Add possible values to usage
- Error out if roles not in the possible values are provided
https://checkmarx.atlassian.net/browse/AST-5288
- Rename TestAuthRegisterWithEmptyUsernameOrPassword to TestAuthRegisterWithEmptyParameters
- Add call in TestAuthRegisterWithEmptyParameters with missing --roles
- Add roles to TestAuthRegister
- Add unit test

AST-5288 auth register should require role

---

internal/commands/util/usercount/github.go
internal/commands/util/usercount/user-count.go
internal/wrappers/github-http.go
internal/wrappers/github.go
internal/wrappers/mock/github-mock.go

when executing the github command, bind the SCMTokenFlag from the running command to viper
https://checkmarx.atlassian.net/browse/AST-9551
N/A

AST-9551 CLI | Create user-count command for Github SCM

---

internal/commands/result.go
internal/commands/scan.go

> Ignoring the 'Not Exploitable' results from counting in result summaries and threshold limits.
>

Ignoring 'Not Exploitable' results

---

internal/commands/result.go
internal/wrappers/results-modifier.go
internal/wrappers/results-sarif.go
test/integration/user-count-github_test.go

- Added security-severity to sarif output

Added new filed to sarif output

---

README.md
internal/commands/auth.go
internal/commands/project.go
internal/commands/root.go
internal/commands/scan.go
internal/commands/util/usercount/gitlab.go
internal/logger/utils.go
internal/params/flags.go
internal/wrappers/azure-http.go
internal/wrappers/bfl-http.go
internal/wrappers/bitbucket-http.go
internal/wrappers/client.go
internal/wrappers/github-http.go
internal/wrappers/gitlab-http.go
internal/wrappers/predicates-http.go

- Sanitize function to include ssh values

Update sanitize function

---

.github/workflows/ast-scan.yml
.github/workflows/release.yml
Dockerfile
test/integration/data/Dockerfile

Docker image update

---

internal/wrappers/client.go
internal/wrappers/results-http.go

change results command to not print body

---

internal/wrappers/azure-http.go

Change Azure API version to 5.0 to support Azure 2019
https://checkmarx.atlassian.net/browse/AST-12510
Already existing tests

AST-12510 support Azure API version 5.0

---

README.md

The install instructions for Windows says to set GOARCH=am. It should say GOARCH=amd64 like the other operating systems. There's no impact on the CLI operation.
None.
>
Does not change the operation of the CLI so no testing needed.
- [NA] I have added documentation for new/changed functionality in …

GOARCH variable for windows should be amd64

---

internal/params/flags.go
test/integration/auth_test.go
test/integration/scan_test.go

>Increased default flag timeout value to 20
> https://checkmarx.atlassian.net/browse/AST-13458
> Existing test cases should pass. Tested the retry mechanism using local tests

Increase retry timeout flag default value

---

internal/commands/scan.go

I think report must be generated even if scan fail because of thresholds.
https://github.com/Checkmarx/ast-cli/issues/415
Not tested yet.

fix: report generation when thresholds fail scan fix #415

---

.github/workflows/ci.yml

Add base auth uri variable for CI instead of using the scan base auth uri
N/A
N/A

Add base auth uri variable for CI

---

internal/commands/scan.go
internal/logger/utils.go
internal/wrappers/uploads-http.go
test/integration/scan_test.go
test/integration/util_command.go

When zipping directories or unzipping for filtering, cleanup any created temporary files.
AST-12968
Assert no files exist of pattern cx-*.zip in the temp dir after creating a scan

Clean temporary files after zipping

---

internal/wrappers/client.go
test/integration/auth_test.go
test/integration/scan_test.go

> Added additional logic to check if API key exists in configuration and extract the base auth uri.
> https://checkmarx.atlassian.net/browse/AST-14323
> Added the test case to run the scan with api key and new flow

Extract tenant and base auth URI from API Key

---

internal/commands/result.go
internal/commands/util/remediation.go
internal/commands/util/remediation_test.go
internal/logger/utils.go
internal/params/flags.go
internal/wrappers/remediation/package-remediation-npm.go
internal/wrappers/results-sca-package.go
test/integration/auth_test.go
test/integration/util_remediation_test.go

Improve SCA details and remediation:
- Add supportsQuickFix to ScaPackageCollection and each DependencyPath head entry
- Allow getting a list of files in the SCA remediation command and rename the flag to package-files
- Apply remediation in devDependencies for NPM
https://checkmarx.atlassian.net/browse/AST-14167

Improve SCA details and remediation

---

internal/commands/scan.go
internal/logger/utils.go
test/integration/scan_test.go

Warn when dangling symbolic links is found instead of failing
00143952
Assert the warning in the broken link test

Warn when dangling symbolic links is found instead of failing

---

internal/commands/scan.go
internal/commands/scan_test.go
test/integration/scan_test.go

Threshold flag issues while whitespaces at the end
Example:
`
./cx.exe scan create --scan-types kics --project-name project-s https://github.com/checkmarx/project--branch main --threshold "kics-low=  1      " 
`
was getting a parsing error while trying to convert the limit value (string) to an integer.
Now it's possible to see this error in logs, and you will not get an error putting whitespace at the end of the threshold value
https://checkmarx.atlassian.net/browse/AST-17738?atlOrigin=eyJpIjoiOTQ1NjJjZTZmNGUxNDQ3NWEyMzYwOTQ2ZjM1OTQzOGUiLCJwIjoiaiJ9
Unity tests
and 
Integration tests

Fix for threshold

---

internal/commands/result.go
internal/commands/scan.go
internal/params/flags.go

Changes in KICS Platform Flag helper
when typed: 
`cx scan create --help`
helper will print:
` --kics-platforms strings       KICS Platform Flag. Use ',' as the delimiter for arrays.`
https://checkmarx.atlassian.net/browse/AST-15470?atlOrigin=eyJpIjoiMDVmNWM2ZTgzMzU0NDBjNWJjMWM1OGFmOTBiYTkxOWYiLCJwIjoiaiJ9
Manual tests

Improving --kics-platforms flag helper

---

internal/commands/result.go
test/integration/scan_test.go

Not run api security when the scanner is not selected.

Fix api security

---

internal/logger/utils.go
internal/wrappers/auth-http.go
internal/wrappers/client.go
internal/wrappers/uploads-http.go

Improve memory usage when uploading zip and limit request dump for printing to 1MB
- General warning cleanup
https://checkmarx.atlassian.net/browse/AST-22649
N/A (performance improvements)

AST-22649 Improve memory usage when uploading zip and limit request dump for printing to 1MB

---

.github/workflows/ci.yml
cmd/main.go
internal/params/binds.go
internal/params/envs.go
test/integration/auth_test.go
test/integration/util_command.go

Add environment variable CX_HTTP_PROXY to override HTTP_PROXY
AST-23205
Test that succeeds authentication with HTTP_PROXY environment variable and then fails authentication with an invalid value in CX_HTTP_PROXY while keeping the HTTP_PROXY value

Add environment variable CX_HTTP_PROXY to override HTTP_PROXY

---

internal/commands/scan.go

- Fixing nil value in kics realtime results. When there are 0 results the field is populated with an empty string.
- https://checkmarx.atlassian.net/browse/AST-27057
- Integration and unit tests

adding empty array to results field instead of nil

---

internal/wrappers/azure-http.go
internal/wrappers/bitbucket-http.go
test/integration/user-count-azure_test.go

Paging support for azure requests.
before paging:
after paging:
Command example: 
`./cx utils contributor-count azure --url-azure https://url.test --orgs Checkmarx --token T0K3N51N15tR0CH3CKM4RX --debug
`
https://checkmarx.atlassian.net/browse/AST-28003?atlOrigin=eyJpIjoiZmYwMDAyMDVmZTkyNDg2MTg1MTg4MTY1MGU4ZDZiYjIiLCJwIjoiaiJ9
integration tests

Paging support for azure wrapper

---

internal/commands/chat.go
internal/commands/root.go
internal/params/binds.go
internal/params/envs.go
internal/params/flags.go
internal/params/keys.go
internal/wrappers/client.go

add new flag to ignore proxy

---

.github/workflows/ci.yml
internal/commands/scarealtime/sca-realtime-utils.go
internal/wrappers/azure-http.go
internal/wrappers/bfl-http.go
internal/wrappers/bitbucket-http.go
internal/wrappers/bitbucketserver/bitbucket-server-http.go
internal/wrappers/client.go
internal/wrappers/github-http.go
internal/wrappers/gitlab-http.go
internal/wrappers/learn-more-http.go
internal/wrappers/logs-http.go
internal/wrappers/pr-http.go
internal/wrappers/predicates-http.go
internal/wrappers/projects-http.go
internal/wrappers/response.go
internal/wrappers/results-pdf-http.go
internal/wrappers/results-sbom-http.go
internal/wrappers/risks-overview-http.go
internal/wrappers/scans-http.go
internal/wrappers/tenant-http.go

https://checkmarx.atlassian.net/browse/AST-28062?atlOrigin=eyJpIjoiN2U0NWRjMjYyMGUzNGE5MzkyZDk0YWExZmFmOGNmZjciLCJwIjoiaiJ9

Timeout and retry flags support for bitbucket, azure, github and gitlab wrappers 

---

.github/workflows/one-scan.yml
internal/commands/result.go

Fix to always generate a pdf report using engines gotten on the scan if "report-pdf-options" flag value is default
https://checkmarx.atlassian.net/browse/AST-30015?atlOrigin=eyJpIjoiZTgzODI3M2VmZGNkNDgxNDgxMzlmOGIwM2IyMDRiNTAiLCJwIjoiaiJ9

Fix for pdf report not using default engines

---

internal/commands/scan.go
internal/commands/scan_test.go

https://checkmarx.atlassian.net/browse/AST-30151?atlOrigin=eyJpIjoiNzA4MWY4OGRmM2NiNDYzYWJkY2I1NGQwNmQ2NDA5YWYiLCJwIjoiaiJ9
unity tests

improving SCA exploitable path validations

---

internal/commands/result.go
internal/commands/result_test.go
internal/commands/util/printer/printer.go
internal/wrappers/results-gl-sast.go
test/integration/result_test.go

AST-25406 Add gl-sast report

---

internal/commands/scan.go

After running a scan using --sca-resolver flag and --sca-resolver-params "--log-level=Verbose"
A log is created and inside a log folder, we can find a folder that should be defined by the project name flag value. 
before fixing, inside the log folder, the folder was always created and named "project-name":
after fix:
https://checkmarx.atlassian.net/browse/AST-31127?atlOrigin=eyJpIjoiZmZmM2JhOGFmNDM0NGI1N2IzOWY3MTMwYWE4YWRkNjMiLCJwIjoiaiJ9
manual tests

Fix for CLI always create a folder with the name 'project-name' and not a given project name

---

internal/commands/scarealtime/sca-realtime-utils.go
internal/commands/scarealtime/sca-realtime.go
internal/commands/scarealtime/sca-realtime_test.go

Add missing package manager types.
https://checkmarx.atlassian.net/jira/software/c/projects/AST/boards/471?assignee=712020%3A8b115cb9-1cab-4fd5-9878-130ce7842e3f&selectedIssue=AST-38138
Add unit test.
Run tests locally

CLI | Add Missing PackageManager Types (AST-38138)

---

internal/commands/scan.go
internal/commands/scan_test.go
internal/params/flags.go
internal/wrappers/scans.go
test/integration/scan_test.go

> Create --sast-fast-scan flag in the scan create command with the value true/false
>https://checkmarx.atlassian.net/browse/AST-37706
> https://checkmarx.atlassian.net/browse/AST-36800
> Added unit and integration tests.

CLI | Fast Scan configuration in SAST scanner (AST-37706)

---

internal/commands/scan.go
internal/commands/scan_test.go

Add threshold user input validation
https://checkmarx.atlassian.net/browse/AST-40169
* Run tests localy
* Added unit tests

CLI | Add threshold user input validation  (AST-40169)

---

.github/workflows/release.yml
internal/commands/.scripts/integration_up.sh
internal/commands/.scripts/up.sh
internal/commands/scan.go
internal/wrappers/client.go
internal/wrappers/mock/application-mock.go

> Fix project association polling issue
> https://checkmarx.atlassian.net/jira/software/c/projects/AST/boards/471/backlog?selectedIssue=AST-40286
> manual testing done, unit & integration are verifying association, but without new access management, it'll be in unit & integration tests after FF will be open

Fix project association polling issue (AST-40286)

---

go.mod
internal/commands/result.go
internal/commands/scan.go
internal/commands/scan_test.go
internal/wrappers/results-http.go
test/integration/root_test.go

> SCA have a different endpoint for the scan results, don't make this call for threshold
> https://checkmarx.atlassian.net/browse/AST-42820?atlOrigin=eyJpIjoiMWVhOGFkZDJiNWFkNDE5NjlhN2NmMzIwZDc5MDc4NzQiLCJwIjoiaiJ9
> Add tests + manual

Dont Call SCA for Threshold AST-42820

---

go.mod
internal/commands/scan.go
internal/commands/scan_test.go
internal/params/filters.go

> Filtering out folders generated by IDEs (.vs, .vscode and .idea) by default when triggering a scan.
> https://checkmarx.atlassian.net/browse/AST-34978
> Added unit tests to check the behavior of filtering out the default folder.

Filtering out default IDE folders in a project for a scan (AST-34978)

---

internal/wrappers/results-pdf-http.go
test/integration/scan_test.go

> Increase the download timeout from 30 sec to 420 seconds (7 min)
because a big PDF takes time to download 
> https://checkmarx.atlassian.net/browse/AST-42743
>

AST-42743 Update results-pdf timeout to 7 minutes

---

internal/commands/result.go
internal/commands/result_test.go

> Show response in console also for a partial scan.
> https://checkmarx.atlassian.net/browse/AST-44163
> Modified an existing test.

Show response to console also in case of partial scan (AST-44163)

---

internal/commands/scan.go
internal/commands/util/utils.go
test/integration/data/project-with-directory-symlink/check/originalFolder.html/csharp-no-vul.cs
test/integration/data/project-with-directory-symlink/originalFolder.html
test/integration/scan_test.go

> The error occurred when we check if symbolicLink to a folder is a directory. I added another validation to check the value that it point at.
> https://checkmarx.atlassian.net/browse/AST-45529
> Added integration test

CLI | Add check to symbolicLink value (AST-45529)

---

.github/workflows/ci.yml

> create docker image in the via pr and scan it with trivy
> https://checkmarx.atlassian.net/browse/AST-43807

AST-43807 create and scan image with trivy when PR created

---

internal/commands/result.go
internal/commands/scan.go

>In the past, we suppressed the exception and did not return an error if there was a failure. Now, we are reverting to the previous state and ensuring that an error is returned if there is a failure because the SAP error could not be reproduced. This decision was confirmed after checking with Michael Kubiaczyk, who used a SAP account for verification.
>https://checkmarx.atlassian.net/browse/AST-43867
>https://checkmarx.atlassian.net/browse/AST-42820

revert  'not showing errors from SCA for threshold' (AST-43867)

---

internal/commands/util/utils.go
internal/services/vorpal_test.go
test/integration/data/symlink-relative-path-folder/datas.html
test/integration/data/symlink-relative-path-folder/test/datas.html/cx_result.json
test/integration/scan_test.go

> An error occurred while checking the target value of a symbolic link that points to a directory or a file. When a symbolic link points to a file/folder and shares a common path, the ReadLink function returns a relative path instead of the full path, causing a flow error.
> https://checkmarx.atlassian.net/browse/AST-45529
> Added integration test

CLI | Add check to symbolicLink value with relative path (AST-45529)

---

internal/commands/scan.go
test/integration/scan_test.go

> The bug was when you create a scan with the same name in branch as in a previous scan but with spaces, it doesn't differentiate and creates with the same name in branch
The solution - delete spaces and thus identify that it is the same branch and therefore no more will be opened
> https://checkmarx.atlassian.net/browse/AST-63539
> Creating 2 scans, one with a normal branch name and the other with spaces, finally check if the names are the same (deleting spaces)
>
> Please include any manual steps for testing end-to-end or …

Remove spaces from branch name to prevent duplication (AST-63539)

---

internal/commands/result.go
internal/commands/result_test.go

> Eclipse & visual studio extension, display description incorrectly if vulnerability has ""
> https://checkmarx.atlassian.net/browse/AST-40454
>

Display the description result incorrectly if the vulnerability contains quotation (AST-40454)

---

internal/services/groups.go
internal/services/projects.go
internal/services/projects_test.go
internal/wrappers/mock/groups-mock.go

> update groups when creating a new project, in the first request of creation
> https://checkmarx.atlassian.net/browse/AST-64011
> refactor 2 unit-tests that don't get now the project ID due to the fact that we broke the flow before the create
>add a new unit-test to check a case of creating successfully a new project with 2 existing groups

update groups when creating a new project(AST-64011)

---

internal/commands/result.go
internal/commands/result_test.go

> Fix total issues counter when SCS FF is off
> https://checkmarx.atlassian.net/browse/AST-63998
> Run tests locally

CLI | Fix TotalIssues=-1 when SCS FF is off (AST-63998)

---

internal/commands/result.go
internal/wrappers/export.go
internal/wrappers/results-sca-package.go

Add snooze or mute check for sca vulnerabilities

---

internal/commands/scan.go
internal/commands/scan_test.go

>Support SCS engine with scan create --resubmit coomand_ add tests for two cases (with scoreCard and with out).
> https://checkmarx.atlassian.net/browse/AST-63906
> Two Unit Tests: First for adding scoreCard in the scan with resubmit ( added Token flag and Url flag) and second without ScoreCard

Support scs  engine In scan create Resubmit command (AST-63906)

---

Dockerfile
go.mod
internal/wrappers/export-http.go

Update go version and chainguard version to fix CVEs

---

.github/workflows/release.yml
.goreleaser.yml

> Implement container signing for Docker images to comply with FedRAMP requirements
> https://checkmarx.atlassian.net/browse/AST-51994

 Implement Container Signing for Docker Images (AST-51994)

---

.github/workflows/release.yml
.goreleaser.yml

Sign docker image (AST-51994)

---

Dockerfile

Update FIPS Bash image To Chainguard Image (AST-0000)

---

internal/commands/scan_test.go
internal/params/filters.go

The node modules directory has been excluded from the scan to optimize performance by reducing the number of files scanned." 
https://checkmarx.atlassian.net/browse/AST-70022
Add unit tests to check if the node modules directory is correctly filtered

Exclude node modules folder from the scan. (AST-70022)

---

.github/workflows/ci.yml
.github/workflows/one-scan.yml
.github/workflows/trivy-cache.yml

> Simple update of trivy scan and add trivy cache.
> No references.
> Out of scope.

AST-000 | Add trivy-cache and update trivy-scan

---

.github/workflows/pr-linter.yml
Dockerfile
go.mod
go.sum
internal/commands/util/pr.go
internal/commands/util/pr_test.go
internal/params/flags.go
internal/wrappers/pr.go
test/integration/pr_test.go
test/integration/root_test.go

> 1. add code-repository-url optional flag
> 2. support PR decoration command for github & gitlab on-prem
> unit test for the new optional flag
>
> manually E2E tests on on-prem machines

Add Code Repository Flag & Support PR Decoration For GH/GL On-prem (AST-72979, AST-72975)

---

internal/commands/result.go
internal/commands/result_test.go

>Removed the DefaultAgent from the unsupportedTypesByAgent map in the filterScsResultsByAgent function because it supports all result types (SCSScorecardType and SCSSecretDetectionType). Since its exclusion list was empty, its presence in the map was redundant. This change simplifies the code without affecting functionality, as DefaultAgent never excluded any result types.
>https://checkmarx.atlassian.net/browse/AST-68004
> Describe how this change was tested. Be specific about anything not tested and reasons why. If this solution has …

Remove default from unsupported agents for SCS results (AST-68004)

---

internal/commands/scan_test.go
internal/params/filters.go

Added support for 'rs' files in scans.
https://checkmarx.atlassian.net/browse/AST-68753
Added a unit test to check the filter method.

Added support for rs files. (AST-68753)

---

internal/commands/result.go
internal/commands/scan.go
internal/services/policy-management.go
internal/services/policy-management_test.go

remove second call to export service in calculating threshold
> Optimize threshold calculation to use the results we are getting in the beginning, instead of getting the results all over again.
> Skip policy evaluation when agent is and IDE agent
> https://checkmarx.atlassian.net/browse/AST-70015
> added unit tests

CLI | Improve Performance In Results Show Command (AST-70015)

---

internal/commands/scan.go
internal/commands/scan_test.go

…lver
> Remove the scaResultsFile after remove the .json suffix
> https://checkmarx.atlassian.net/browse/AST-48074
> Unit Test (TestRunScaResolverAndAddScaResultsFileCleanup)
Mock Setup: Defined mock values for sourceDir, scaResolver, and projectName.
Function Execution: Called runScaResolver with the mock inputs.
File Deletion Check: Verified that the temporary file was deleted using os.Stat and os.IsNotExist, ensuring that the cleanup process worked as expected.
>
> Please include any manual steps for testing end-to-end or …

Deleting a copy file of sca.json when scan runnig with ScaResolver  (AST-48074)

---

internal/commands/groups.go
internal/commands/project.go
internal/services/groups.go
internal/services/groups_test.go
internal/services/projects.go

> Project Creation Flow With AM Phase 2
>

Project Creation Flow With AM Phase-2 (AST-72966)

---

.golangci.yml
go.mod
go.sum
internal/wrappers/client.go
internal/wrappers/codebashing-http.go
internal/wrappers/jwt-helper.go
test/integration/scan_test.go

> Upgrade JWT package from 3.2.2 to 5
>

Vul Fix - Upgrade JWT Package From 3.2.2 To 5 (AST-74171)

---

internal/services/projects.go
internal/services/projects_test.go

> Fix Primary branch deletion in CxOne
> https://checkmarx.atlassian.net/browse/AST-74968
> Change existing tests

CLI | Fix Primary branch deletion in CxOne (AST-74968)

---

internal/commands/asca/asca-engine.go
internal/commands/asca/asca-engine_test.go
internal/commands/scan.go
internal/services/asca.go
internal/services/asca_test.go
internal/wrappers/jwt-helper.go
internal/wrappers/mock/jwt-helper-mock.go

> Removed the FF call to PACKAGE_ENFORCEMENT_ENABLED and just checking if the licenses contains AI Protection license
> https://checkmarx.atlassian.net/browse/AST-77073
> X

Remove package enfoorcement FF check in asca command (AST-77073)

---

internal/commands/project.go
internal/commands/project_test.go
internal/params/flags.go
test/integration/project_test.go

> Project list command filtered by tag with empty values (project without tag)
> https://checkmarx.atlassian.net/browse/AST-48293
>

Project list command filtered by tag with empty values - project without tag (AST-48293)

---

.github/workflows/ci.yml
internal/commands/scan.go
internal/commands/scan_test.go
internal/wrappers/mock/uploads-mock.go

> Clean temp folder upon any CLI failure.
> https://checkmarx.atlassian.net/browse/AST-77958
>

Clean temp folder upon any CLI failure(AST-77958)

---

Dockerfile
internal/commands/scan.go
internal/commands/scan_test.go
internal/wrappers/export-http.go

…on base on user input
> Fix fast scan and incremental scan initialization in SAST configuration.
> https://checkmarx.atlassian.net/browse/AST-80553
> https://checkmarx.atlassian.net/browse/AST-80586
> https://checkmarx.atlassian.net/browse/AST-79107
> Added UT for all cases

CLI | Fix fast scan and incremental scan initialization in SAST configuration (AST-79107, AST-80586, AST-80553)

---

.github/workflows/ci.yml
.github/workflows/release.yml
Dockerfile
internal/commands/scan.go
internal/commands/util/remediation.go

Downgrade kics real time to version v2.1.3 instead of latest

---

internal/commands/scan.go
internal/params/flags.go
internal/wrappers/scans.go
test/integration/scan_test.go

> Added filter flags for Containers config scan.
> https://checkmarx.atlassian.net/browse/AST-82260
> Added integration tests

CLI | Container Security filter flags (AST-82260)

---

internal/wrappers/client.go
internal/wrappers/client_test.go
internal/wrappers/constants.go
internal/wrappers/projects-http.go
internal/wrappers/scans-http.go
internal/wrappers/scans-http_test.go
internal/wrappers/wrapper-constants.go

Implemented retry logic and use both Scans and Project APIs within the Scans service to address 502 errors.

Add retry mechanism to 502 response (AST-82566)

---

internal/commands/result.go
test/integration/scan_test.go

When try to getting the policy management step, the user receive a message indicating that the scan is currently running and policy management step is being skipped.
https://checkmarx.atlassian.net/browse/AST-81796
Add integration test that try to show results before the scan finished.

Skip of policy evaluated when the scan not finished(AST-81796)

---

Dockerfile
internal/wrappers/client.go
internal/wrappers/client_test.go

> Ensure writeCredentialsToCache is thread-safe, Prevent multiple Goroutines from overwriting the cache inconsistently.
> https://checkmarx.atlassian.net/browse/AST-82856
> Add unit test

Make writeCredentialsToCache func thread safe (AST-82856)

---

test/integration/predicate_test.go

*https://checkmarx.atlassian.net/browse/AST-84248

Add integration test for triage update and show with custom states (AST-84248)

---

internal/commands/scan.go
internal/commands/scan_test.go
test/integration/scan_test.go

Handling bug where in the scenario of passing --scan-types "scs" and not specifying scorecard specific flags such as token and repo, an error would be triggered, blocking further execution. The correct behavior is that scorecard should be skipped and a warning should be displayed while secret-detection should run. This PR addresses this by only giving error if scorecard is specifically stated to run with --scs-engine flag set to scorecard.
[AST-93338](https://checkmarx.atlassian.net/browse/AST-93338)
Now:
Previously:
*Add any other relevant …

Fix SCS error message when no Scorecard flags are set (AST-93338)

---

internal/commands/scan.go
internal/commands/scan_test.go
test/integration/scan_test.go

*Display Scaresolver error message when the required fields are not valid.*
**Issue/Bug**
If customer has passed ScaResolver path --sca-resolver  with Source as Zip, the Scan used to get triggered from CxOne SCA scan and not using offline SCA Resolver. Offline Sca-Resolver does not support the zip source
**Fix Added** : 
When Scan create is triggered with source  as zip and scaResolver path is set 
**Error is displayed as : Scanning Zip files is not supported by ScaResolver. Please use non-zip source**

Scan Create command: Fix for Source zip with ScaResolver issue (AST-73409)

---

internal/commands/data/manifests/requirements.txt
test/integration/data/manifests/requirements.txt

*Fix Sca Vulnerability urllib3 ,Change from 1.26.30 to 2.5.0*

Fix Sca Vulnerability urllib3 ,Change from 1.26.30 to 2.5.0 (AST-0000)

---

internal/commands/result.go
internal/commands/result_test.go
internal/wrappers/feature-flags.go

*Removing the FF NEW-SAST-SCAN-RESULT-ENABLED as its enabled for all the customers in production. *
Removing the logic when flag is off

Removed feature flag new-sast-scan-result-enabled(AST-99956)

---

internal/services/realtimeengine/secretsrealtime/config.go
internal/services/realtimeengine/secretsrealtime/secrets-realtime.go
internal/services/realtimeengine/secretsrealtime/secrets-realtime_test.go

Fix Duplicate Secret Realtime Results In MultiLine (AST-0000)

---

.github/workflows/ci.yml
.golangci.yml
go.mod
go.sum
internal/commands/hooks.go
internal/commands/pre-receive.go
internal/commands/pre_commit.go
internal/commands/pre_receive_test.go
internal/wrappers/mock/jwt-helper-mock.go
test/integration/data/pre-receive-data/excludeFile.yaml
test/integration/data/pre-receive-data/excludeFolder.yaml
test/integration/data/pre-receive-data/ignoreResultId.yaml
test/integration/data/pre-receive-data/ignoreRuleId.yaml
test/integration/pre-receive_test.go

*Commands for Pre receive hook feature for secret detection .*

Pre receive feature command  (AST-89345)

---

.github/workflows/ci.yml
internal/commands/asca/asca-engine.go
internal/commands/containers-realtime-engine.go
internal/commands/data/containers/testdata/ignoredContainers.json
internal/commands/data/ignoredAsca.json
internal/commands/scan.go
internal/services/asca.go
internal/services/asca_test.go
internal/services/realtimeengine/containersrealtime/config.go
internal/services/realtimeengine/containersrealtime/containers-realtime.go
internal/services/realtimeengine/containersrealtime/containers-realtime_test.go
internal/services/realtimeengine/iacrealtime/config.go
internal/services/realtimeengine/iacrealtime/iac-realtime.go
internal/services/realtimeengine/iacrealtime/iac-realtime_test.go
internal/wrappers/grpcs/asca.go

Add ignore file support for IAC, ASCA, and Containers with filtering tests(AST-107986)

---

internal/services/realtimeengine/iacrealtime/config.go
internal/services/realtimeengine/iacrealtime/mapper.go

Add ExpectedValue and ActualValue fields to IacRealtimeResult (AST-0000)

---

go.mod
go.sum

upgrade parser version - look for package per section name(AST-000)

---

internal/commands/scan_test.go
internal/constants/errors/errors.go
internal/services/applications.go
internal/services/applications_test.go
internal/services/projects.go
internal/wrappers/application-http.go
internal/wrappers/application.go
internal/wrappers/feature-flags.go
internal/wrappers/mock/application-mock.go
test/integration/predicate_test.go
test/integration/scan_test.go

Existing project Assignment to Existing Application (AST-108181)
