internal/wrappers/configuration.go

in Windows, this fixes this. The configuration files are no longer
hidden in the folder either.

ClI wasn't creating .checkmarx folder in user home directory correctly

---

.github/dependabot.yml
Dockerfile

- Update Docker Image
- Add Dependabot configuration

Update Docker Image

---

.circleci/config.yml

Added the context to use AWS in the config.yml file

changed the config.yml file

---

.circleci/config.yml
internal/commands/configuration.go
internal/commands/root.go
internal/commands/utils.go
internal/params/flags.go
internal/wrappers/client.go
internal/wrappers/configuration.go

- Denial_Of_Service_Resource_Exhaustion in configuration.go line 123

Resolving vulnerabilities detected by Checkmarx:

---

cmd/main.go

- add tenant support for auth register command

add tenant name to register auth

---

README.md
internal/commands/configuration.go

clean readme and add cx_tenant to description

---

README.md

- (configure set) now has user specify property to update with (--prop-name) and (--prop-value) options.

Updated documentation to reflect changes (confgure set) command.

---

.goreleaser.yml

release to checkmarx registry

---

internal/wrappers/results-http.go

The API is returning empty results causing failures in the CLI testing process. This mock added temporary results data. For authenticity the API call is still made but the results are overwritten by the CLI.

Mocked results returned from API.

---

.github/workflows/release.yml
.goreleaser.yml
Dockerfile
goreleaser/Dockerfile

fix go releaser

---

README.md

Updated tag version.

---

.goreleaser.yml

* add cgo flag to release build

added cgo flag

---

internal/wrappers/configuration/configuration.go

permission correction

---

internal/commands/scan.go

* Added workflow logs in verbose mode

add workflow logs in verbose mode

---

internal/commands/result.go
internal/commands/scan.go

* result summary only when not using nowaitflag 
* added default result filename
* using filepath to set result path location

small improvements to results

---

internal/commands/scan.go
internal/commands/util/utils.go

- the initial slash was adding an empty folder in the top of the zip
- fix utils command, it was triggering the "configure" prompt

Change zip base dir to "" instead of "/"

---

internal/commands/scan.go

- fix return code in scan create

Fix return code 

---

internal/params/flags.go

- change default retry to 3 times

change default retry to 3

---

.goreleaser.yml
internal/commands/root.go

Adding autocomplete in goreleaser to homebrew

Adding autocomplete in goreleaser to homebrew

---

internal/wrappers/groups-http.go

- Change tenant flag replacement position

Fix groups tenant flag

---

internal/wrappers/results-json.go
internal/wrappers/results-utils.go

- Convert negative columns to one

Convert column negative values to 1

---

internal/commands/result.go

* validation on the number of nodes

Check if if SAST contains more than one node

---

internal/commands/result.go

- Filter results before converting to sonar

remove SCA results

---

internal/commands/predicates.go
internal/commands/scan.go
internal/params/flags.go
internal/wrappers/mock/predicates-mock.go
internal/wrappers/predicates-http.go
internal/wrappers/predicates.go
test/integration/scan_test.go

New threshold limit flag

---

internal/commands/scan.go
test/integration/scan_test.go

edit threshold message log

---

internal/commands/result.go
internal/commands/scan.go
internal/params/flags.go
internal/wrappers/mock/results-mock.go
internal/wrappers/results-json.go
internal/wrappers/results-modifier.go

- When parsing description, always set it to the top level of the result and remove it from "data" if it came from it
- Rename labels/functions to kics/sca from infrastructure/dependency
- Code formatting
Match the API changes for the description fields.
https://checkmarx.atlassian.net/browse/AST-8622
Successful parsing in the existing integration tests will test this change.

AST-8622 SAST Description

---

internal/commands/result.go
internal/commands/result_test.go
internal/commands/util/printer.go
test/integration/result_test.go

add summaryjson report format

---

internal/wrappers/predicates-http.go

Handle error when doing predicate calls to avoid panicking when credentials are wrong.
Case 00102427
N/A

 Handle error in predicate calls

---

internal/commands/root.go
internal/commands/scan.go
internal/params/flags.go
test/integration/scan_test.go

> Renaming of 'format' flag to 'scan-info-format' for scan create command.
https://checkmarx.atlassian.net/jira/software/c/projects/AST/boards/27?modal=detail&selectedIssue=AST-5575
https://checkmarx.atlassian.net/jira/software/c/projects/AST/boards/27?modal=detail&selectedIssue=AST-8683
> Describe how this change was tested. Be specific about anything not tested and reasons why. If this solution has unit and/or integration testing, tests should be added for new functionality and …

Rename 'format' to 'scan-info-format'

---

internal/commands/scan.go

Updated the help text for SCA Resolver.

---

internal/commands/scan.go

> Fix threshold documentation
> None
> Not required

fix threshold documentation

---

internal/commands/scan.go
internal/wrappers/predicates-http.go

- Return empty list on triage show for SCA
- On triage update for SCA, throw error
- Validate if scan-timeout is > 0
https://checkmarx.atlassian.net/browse/AST-8492
Current triage and timeout tests

SCA triage and timeout validation

---

internal/wrappers/client.go

Fix not using proxy when getting token from IAM
N/A
N/A

Use proxy when getting token from IAM

---

internal/commands/result.go
internal/commands/root.go
test/integration/scan_test.go

- Add back result command and make it deprecated.
>
> Please include any manual steps for testing end-to-end or functionality not …

add back result command and make it deprecated

---

test/integration/predicate_test.go
test/integration/project_test.go
test/integration/result_test.go
test/integration/root_test.go
test/integration/scan_test.go
test/integration/util.go

Improvements to Tests

---

internal/commands/scan.go

Remove the default preset. 
>
> Please include any manual steps for testing end-to-end or functionality not covered by …

remove default preset

---

internal/wrappers/codebashing-http.go
internal/wrappers/codebashing.go
internal/wrappers/mock/codebashing-mock.go

Return error if codebashing url claim is not found 
>

return error if cb-url claim is not found

---

cmd/main.go
internal/commands/result.go
internal/commands/result_test.go
internal/params/flags.go
internal/wrappers/ast.go
internal/wrappers/codebashing-http.go
test/integration/result_test.go

* Add different exit codes to codebashing command
>
> Please include any manual steps for testing end-to-end or functionality not …

Add new exit code to codebashing command 

---

.github/workflows/ast-scan.yml
.github/workflows/ci.yml

split checkmarx scan

---

test/integration/auth_test.go

Test modified temporarily to accept the error from AST.

---

internal/wrappers/scans-modifier.go

- Fixed "Created at" to point to the local time;

AST-10848 - CLI | Created At must be in the local timezone

---

internal/commands/result.go
test/integration/data/Dockerfile
test/integration/predicate_test.go

Fixed sca issues

---

internal/commands/result.go
internal/params/filters.go
internal/wrappers/results-json.go

>  Add scanId to the results json 
> [Include supporting link to GitHub Issue/PR number](https://checkmarx.atlassian.net/browse/AST-11604)
> Local testing using the generated results object. The existing tests should run and complete successfully.

added Scan Id in results json

---

internal/wrappers/bitbucket-http.go

Fixing SAST vulnerabilities.

---

internal/commands/result.go
internal/commands/scan.go
internal/commands/scan_test.go
internal/wrappers/results-summary.go
test/integration/scan_test.go

> Added logic to create a report for async scans. The report will be generated in HTML and JSON formats based on the user inputs.
> https://checkmarx.atlassian.net/browse/AST-12482
> Added integration test to make sure the html file is created for async scans and the file contains contents.

Ast 12482 add summary html for async scans

---

.github/dependabot.yml
.github/workflows/dependabot-auto-merge.yml
.github/workflows/pr-automation.yml

- Add github actions for dependabot auto-merge and PR assignee and reviewers

Improve PR handling

---

.github/pr-labeler.yml
.github/release.yml
.github/workflows/pr-label.yml
.github/workflows/release.yml

> Add automatic release notes.

Release notes format improvement

---

.github/workflows/release.yml
internal/commands/scan.go
test/integration/scan_test.go

- Adding teams notification step with auto generated html to display the release notes.
Local testing of the release GitHub action

added auto release notes and teams notification with release details

---

.github/release.yml
.github/workflows/release.yml
.goreleaser.yml

- Adding the correct teams support for the GitHub Action

adding teams notifications 

---

internal/commands/result.go

> BranchName in the summary URL is now encoded to help open the URL directly without causing any issues.
>

BranchName in the summary URL is now encoded.

---

internal/commands/scan.go
internal/commands/scan_test.go
test/integration/scan_test.go

KICS Check different return codes

---

internal/commands/scan.go
internal/params/flags.go

> Added new flag for providing platform options for kics scan. 
>

Added new flag for kics platforms.

---

internal/commands/scan_test.go

Added unit test for flag kics-platforms.

---

internal/commands/util/remediation.go

- Fixing similarity id filter flag
- integration and unit tests

fixing similarity id filter flag

---

.github/workflows/release.yml

Add more info to docker installation step when releasing
N/A
N/A

Add more info to docker installation step when releasing

---

.github/workflows/release.yml

Specify docker version in release workflow.
N/A
N/A

Specify docker version in release workflow

---

.github/workflows/release.yml

Set docker version release
N/A
N/A

Set docker version release

---

.github/workflows/release.yml

Use formula when installing docker
N/A
N/A

Use formula when installing docker

---

internal/commands/scan.go

Add output when sca resolver fails to run. It will provide more details to the user. 
https://checkmarx.atlassian.net/browse/AST-15817

Add output to sca error handling

---

internal/commands/result.go

Use result column + length for EndColumn and add 1 to EndColumn if it equals StartColumn
https://checkmarx.atlassian.net/browse/AST-15787
Existing tests

Use result column + length for EndColumn and add 1 to EndColumn if it equals StartColumn

---

internal/wrappers/results-modifier.go

- Add a check for all unsigned fields similar to what is done for “column” when parsing JSON.
- https://checkmarx.atlassian.net/browse/AST-16027
- Unit and integration tests.

Add a check for all unsigned fields when parsing JSON results

---

README.md
internal/commands/auth.go
internal/commands/project.go
internal/commands/result.go
internal/commands/root.go
internal/commands/scan.go
internal/commands/util/completion.go
internal/commands/util/configuration.go
internal/commands/util/env.go
internal/commands/util/help.go
internal/commands/util/learnmore.go
internal/commands/util/pr.go
internal/commands/util/remediation.go
internal/commands/util/utils.go
internal/wrappers/configuration/configuration.go
internal/wrappers/results-sarif.go

update documentation links

---

internal/commands/scan.go
internal/commands/scan_test.go
internal/params/flags.go
internal/wrappers/mock/scans-mock.go
internal/wrappers/scans.go
test/integration/scan_test.go
test/integration/util_command.go

- Adding resubmit flag under scan create command
- https://checkmarx.atlassian.net/browse/AST-14554
- Unit and integration tests

adding resubmit flag to scan create

---

internal/wrappers/results-http.go

Ignore not found for SCA enrichment.
-
--

add validation for not found

---

internal/wrappers/remediation/package-remediation-npm.go
test/integration/data/package.json

- Fixing error related to non existing dependencies field.
- Unit and integration

Fixing error related to non existing dependencies or devDependencies field

---

internal/logger/utils.go
internal/wrappers/client.go

Sanitize logs for proxy flag
https://checkmarx.atlassian.net/browse/AST-17198
N/A

AST-17198 Add proxy flag to sanitizing list

---

.github/workflows/ci.yml
internal/commands/auth.go
internal/commands/auth_test.go
internal/commands/result.go
internal/commands/result_test.go
internal/commands/root.go
internal/wrappers/client.go
internal/wrappers/codebashing-http.go
internal/wrappers/groups-http.go
internal/wrappers/mock/scans-mock.go
internal/wrappers/uploads-http.go
test/integration/auth_test.go

- Adding the possibility to run commands without the need to use base-uri. Retrieving information from jwt token. 
- https://checkmarx.atlassian.net/browse/AST-17225
- Integration and unit testing.

Getting base-uri from jwt token

---

internal/wrappers/client.go
test/integration/auth_test.go

- Making base-uri and base-auth-uri flags to override token value.
- Integration and unit tests

adding flag overrride

---

internal/wrappers/client.go
test/integration/auth_test.go

fixing problem with base-auth-uri

---

internal/commands/util/usercount/azure.go

Fix total contribution count for azure. 
https://checkmarx.atlassian.net/browse/AST-18034
> Describe how this change was tested. Be specific about anything not tested and reasons why. If this solution has  unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>

fix total commits count

---

internal/commands/.scripts/integration_up.sh
internal/commands/root.go
internal/params/binds.go
internal/params/flags.go
internal/wrappers/client.go
internal/wrappers/codebashing-http.go
internal/wrappers/configuration/configuration.go
test/integration/auth_test.go
test/integration/user-count-gitlab_test.go

give api key priority

---

internal/params/binds.go
internal/params/envs.go
internal/params/keys.go
internal/wrappers/client.go

Fix issue with existing checkmark configuration.
https://checkmarx.atlassian.net/browse/AST-18715

use always default value, don't get the value from config

---

internal/commands/result.go
internal/wrappers/mock/results-mock.go
internal/wrappers/results-http.go
internal/wrappers/results-json.go
internal/wrappers/results-sca-package.go
internal/wrappers/results.go

- Adding IsDirectDependency field to the sca results and distinction between sca vulnerabilities and supply chain.
- https://checkmarx.atlassian.net/browse/AST-17319
- https://checkmarx.atlassian.net/browse/AST-16863
- Integration and unit tests

adding new direct dependency field and sca type to sca results

---

internal/commands/result.go

Fix bug# 20522

---

internal/params/filters.go

Dockerfiles support
https://checkmarx.atlassian.net/browse/AST-19847?atlOrigin=eyJpIjoiZGRiYmQ3ZTM1ODdiNDgwNmIyODE3MTk1M2EzNzE1ZjMiLCJwIjoiaiJ9

AST-19847 - Fixing for dockerfiles support

---

internal/params/binds.go

Increase timeout flag 
Several issues in github action.

increase timeout flag

---

.golangci.yml
cmd/main.go
internal/commands/result.go
internal/commands/result_test.go
internal/commands/root.go
internal/commands/root_test.go
internal/commands/scan.go
internal/commands/util/printer/printer.go
internal/params/binds.go
internal/params/envs.go
internal/params/keys.go
internal/wrappers/mock/results-pdf-mock.go
internal/wrappers/projects-http.go
internal/wrappers/results-pdf-http.go
internal/wrappers/results-pdf.go
test/integration/result_test.go
test/integration/util_command.go

Add PDF report option

---

internal/commands/scan.go
internal/wrappers/jwt-helper.go
test/integration/scan_test.go

Clean scan types

---

.goreleaser.yml

https://checkmarx.atlassian.net/browse/AST-18614?atlOrigin=eyJpIjoiMWU4NDAzMDE2ZTdiNGE1NDllZGQ4MTQzMGMwMWIxZmQiLCJwIjoiaiJ9

ARM Support in goreleaser

---

internal/wrappers/jwt-helper.go
internal/wrappers/utils/utils.go
test/integration/scan_test.go

BUG-JWT-Claims fix

---

internal/commands/result.go

Fixing and preventing nil pointer exception in sarif findResult

---

internal/commands/project.go
internal/commands/scan.go
internal/commands/scan_test.go
internal/wrappers/mock/projects-mock.go
internal/wrappers/projects-http.go
internal/wrappers/projects.go
test/integration/scan_test.go
test/integration/util_command.go

https://checkmarx.atlassian.net/browse/AST-19165?atlOrigin=eyJpIjoiMzk2NjBiNGE0MDk2NGQwZGFjODUxNTE0NWI0OWQ1YzUiLCJwIjoiaiJ9
>
> Please include any manual steps for testing end-to-end or …

AST-19165 - Adding support to override project tags and project groups on scan

---

.github/workflows/release.yml
.goreleaser.yml

https://checkmarx.atlassian.net/browse/AST-22341?atlOrigin=eyJpIjoiMTQ2OTkxNmI2YzU0NGNkMGE0ZTBkYjJjYzk1YTQzYzciLCJwIjoiaiJ9

Adding support to s3 bucket in goreleaser

---

internal/commands/result.go
internal/commands/scan.go
internal/commands/scan_test.go
internal/params/flags.go
internal/wrappers/scans.go
test/integration/scan_test.go

https://checkmarx.atlassian.net/browse/AST-19015?atlOrigin=eyJpIjoiY2JlZGI0NGQ5YzM4NGNjMGE3MzA4MWNkMjZkODdiMTMiLCJwIjoiaiJ9
unity tests and integration tests

ExploitablePath and LastSastScanTime flags

---

internal/params/filters.go

Dart support in BaseFilters 

---

README.md

Add download.checkmarx.com links for each latest release to the readme
N/A
N/A

Add download.checkmarx.com links for each latest release to the readme

---

internal/wrappers/projects-http.go

Increasing the limit on branches api call. 
It refers to a GitHub issue opened on Jetbrains.

Increase branch limit

---

internal/commands/scarealtime/sca-realtime.go
internal/wrappers/results-json.go

add sca realtime errors to results

---

internal/commands/scan.go

adding case for empty kics results

---

internal/logger/utils.go
internal/wrappers/bitbucketserver/bitbucket-server-http.go
internal/wrappers/bitbucketserver/bitbucket-server.go

Filter commits older than 90 days for counting contributors
AST-24259
N/A

AST-24259 Filter commits for past 90 days

---

internal/wrappers/results-summary.go

fix html summary format

---

internal/commands/result.go

replacing N/A to 0 when we actually have the scan type configured and 0 vulnerabilities found
https://checkmarx.atlassian.net/browse/AST-25547?atlOrigin=eyJpIjoiNGEyYzAxNGE4ZmU4NDJjZTg4NmM3OTc2NmQxNmIyNjYiLCJwIjoiaiJ9

Summary results fix

---

internal/commands/scan.go
internal/wrappers/projects-http.go

Increase get project limit to 10000
>

add limit 10000 to get projects

---

internal/commands/scarealtime/sca-realtime-utils.go
internal/commands/scarealtime/sca-realtime.go

> Fix by creating a function to get PackageManager from ResolvingModuleType
> [SCA Realtime returning 0 results](https://checkmarx.atlassian.net/browse/AST-25973)
>

Fix SCA realtime returning 0 results due wrong package manager

---

internal/commands/predicates.go
internal/wrappers/mock/predicates-mock.go
internal/wrappers/predicates-http.go
internal/wrappers/predicates.go

The predicate/triage request was sending the wrong body and getting a 502 error.

Fixing request to predicate/triage

---

internal/commands/result.go

Fix for policies managements

---

cmd/main.go
internal/commands/root.go

https://checkmarx.atlassian.net/browse/AST-30149?atlOrigin=eyJpIjoiYzE5YmZkYjRlNDQ3NDYwNzkyYjNhYjE5MDU3NmEwM2QiLCJwIjoiaiJ9

Printing CLI version if debug is enabled

---

internal/commands/scan.go

Check policies violations 

---

internal/wrappers/github-http.go
internal/wrappers/gitlab-http.go

https://checkmarx.atlassian.net/browse/AST-30571?atlOrigin=eyJpIjoiMWQ2NDkyZTdmNTI1NDk4Nzk3NjU0MWI2MWMyZWJkOGUiLCJwIjoiaiJ9

Fix nil pointer when empty github repo - contributors count

---

internal/wrappers/results-http.go
internal/wrappers/utils/utils.go

sort results by severity

---

internal/commands/result.go

add requested status to pooling pdf

---

.github/workflows/ci.yml
.github/workflows/release.yml
go.mod
internal/commands/.scripts/integration_up.sh
internal/commands/result.go
internal/wrappers/results-sca-package.go
test/integration/auth_test.go
test/integration/result_test.go
test/integration/scan_test.go
test/integration/tenant_test.go
test/integration/util_command.go

Fix sca state

---

internal/wrappers/results-http.go
test/integration/result_test.go

Fix for results total count as zero

---

internal/commands/result.go
internal/wrappers/results-gl-sast.go

correct link for results

---

internal/commands/util/usercount/github.go

[> Include supporting link to GitHub Issue/PR number
](https://checkmarx.atlassian.net/browse/AST-33587)
>
> Please include any manual steps for testing end-to-end or functionality not …

Github contributor count

---

internal/commands/scan.go
internal/commands/scan_test.go

Fix bub gumber AST-337567 - Send MainBarnch value

---

internal/wrappers/feature-flags.go
internal/wrappers/uploads-http.go

- Adding minio feature flag support
- https://checkmarx.atlassian.net/browse/AST-35027
- Manual and integration tests

adding minio feature flag

---

internal/commands/chatsast/sast-prompt.go

Rename gpt fix

---

internal/params/filters.go

Add "*.cmp" extension

---

internal/commands/result.go

Initialize sarif arrays 

---

internal/commands/scan.go

remove sca option from scan logs -h description
https://checkmarx.atlassian.net/jira/software/c/projects/AST/boards/471?assignee=712020%3A8b115cb9-1cab-4fd5-9878-130ce7842e3f&selectedIssue=AST-36193
Checked the changes in my local cli

remove sca optin from scan log description

---

.github/workflows/ci.yml
internal/commands/auth.go

Update CI.yml to Use GitLab Env Vars

---

internal/params/flags.go
internal/wrappers/feature-flags.go

> shared Containers constants
> https://checkmarx.atlassian.net/browse/AST-37225

AST-37225 Shared Containers Constants

---

internal/commands/result.go
internal/commands/result_test.go

> This PR fixes the incorrect "About this vulnerability" link (AST-35994) to direct users to the correct vulnerability information
>https://checkmarx.atlassian.net/browse/AST-35994
>Add unit test to check the creation of the correct vulnerability fix link

Fix "About this vulnerability" link (AST-35994)

---

internal/commands/util/usercount/azure.go
internal/commands/util/usercount/user-count_test.go
internal/params/flags.go
internal/wrappers/azure-http.go
internal/wrappers/azure.go
internal/wrappers/mock/azure-mock.go

Add check if a repo is disabled in GetRepositories function in AzureWrapper
https://checkmarx.atlassian.net/jira/software/c/projects/AST/boards/471?assignee=712020%3A8b115cb9-1cab-4fd5-9878-130ce7842e3f&selectedIssue=AST-37664
Run tests locally

CLI | Handling disabled repos in ADO

---

internal/wrappers/client.go

Implement a mechanism to automatically resend a request to a new location if the response contains a redirected status code. This enhancement will improve the handling of redirected requests within the application.
https://checkmarx.atlassian.net/browse/AST-37864
Run tests locally

CLI | Add redirected request mechanism (AST-37864)

---

test/integration/root_test.go
test/integration/scan_test.go

Increase pollScanUntilStatus timeout
Run tests locally

Increase fullScanWait to 180 sec

---

Makefile
README.md

Revert "Revert "Add Makefile""

---

internal/wrappers/feature-flags-http.go

Fix FeatureFlag Service Null Error- return the http error to the feature flags service

---

.github/scripts/signing_win.sh
.github/workflows/release.yml
.goreleaser-dev.yml
.goreleaser.yml

Added signing process for the windows binaries in the release CI
https://checkmarx.atlassian.net/browse/AST-42438
.

CLI | Signing for the win binary was added to the CI (AST-42438)

---

internal/wrappers/feature-flags.go

Change minio flag default value to true.
>

CLI | Change minio FF default value

---

go.mod
internal/commands/root.go
internal/commands/root_test.go

Revert "Ast 35584"

---

internal/wrappers/groups-http.go
internal/wrappers/jwt-helper.go
internal/wrappers/mock/jwt-helper-mock.go

> changed the way we're pulling the tenant value.
> https://checkmarx.atlassian.net/browse/AST-31008
> Run test locally

CLI | Change get tenant functionality in group wrapper (AST-31008)

---

internal/constants/errors/errors.go
internal/wrappers/uploads-http.go

> Added more indicative error when uploadFile fails. In this error we suggest to the user to check if the domain of the request is in is whitelist.
> https://checkmarx.atlassian.net/browse/AST-46098
> Run test locally

CLI | Add indication in case of failure in UploadFile (AST-46098)

---

.github/workflows/ci.yml

Fix Trivy scan

---

internal/commands/result.go
internal/commands/result_test.go
internal/wrappers/mock/scan-overview-mock.go
internal/wrappers/results-summary.go

- Adding critical severity for scs results in the individual table.
- https://checkmarx.atlassian.net/browse/AST-37694
- Manual, integration and unit tests

Adding critical severity on SCS table

---

internal/commands/result.go

supporting api-sec missing case

---

internal/commands/result.go
test/integration/scan_test.go

Returning an empty array instead of NULL, to meet the requirements of the git lab results schema
https://checkmarx.atlassian.net/browse/AST-63985
Added an integration test to test the report file with the GitLab schema

Fix GitLab dashboard, Dependency Scanning 0 vulnerabilities error. (AST-63985)

---

internal/commands/vorpal/vorpalconfig/vorpal-mac-amd.go
internal/commands/vorpal/vorpalconfig/vorpal-mac-arm.go

> Added support to download and execute vorpal engine for macOS arm64. 
> https://checkmarx.atlassian.net/browse/AST-63697
> X

CLI | Support download and execute of Vorpal engine in MacOS arm64 (AST-63697)

---

CODEOWNERS

Add CodeOwner file

---

internal/wrappers/export-http.go

> Remove BOM prefix if exist in export service response
> https://checkmarx.atlassian.net/browse/AST-66827
> X

Removed BOM prefix from response body of export service (AST-66827)

---

Dockerfile

update chainguard version

---

internal/commands/result.go

CLI | Fix SCS Engine Name

---

.github/workflows/release.yml

> Upgrade setup docker on macos github action
> https://checkmarx.atlassian.net/browse/AST-68752
> X

CLI | Upgrade setup docker on macos github action (AST-68752)

---

.github/workflows/release.yml

commit qemu

---

.github/workflows/release.yml

Integrate cosign for Docker image signature verification

---

.github/workflows/release.yml
.goreleaser.yml

Revert " Implement Container Signing for Docker Images (AST-51994)"

---

.github/workflows/release.yml
.goreleaser.yml
Dockerfile

Update container signing Docker image (AST-51994)

---

Dockerfile

> This Dockerfile sets up the Checkmarx CLI  using a FIPS-compliant bash base image.
It's designed to provide a secure environment for running Checkmarx scans in compliance
> https://checkmarx.atlassian.net/browse/AST-66846
>

Dockerfile for Checkmarx CLI with FIPS (AST-66846)

---

.goreleaser.yml

Change to secrets from ENV (AST-51994)

---

.github/workflows/release.yml
.goreleaser.yml

Revert sign docker  (AST-51994)

---

internal/services/projects.go
internal/wrappers/mock/projects-mock.go

> Support Comma In Project Name.
>

Support Comma In Project Name

---

internal/commands/scan.go
internal/logger/utils.go

> SSCS repository token and URL sanitization.
> https://checkmarx.atlassian.net/browse/AST-65312
>

Obfuscate github repo token for scorecard (AST-65312)

---

go.mod
go.sum

> Fix bug containers-resolver in windows (AST-70674)
>

Fix bug containers-resolver in windows (AST-70674)

---

gonMac.hcl

Fix gonMac.hcl (AST-0000)

---

internal/params/filters.go

Added support for 'jsx' files in scans.
https://checkmarx.atlassian.net/browse/AST-70294

Support for jsx files (AST-70294)

---

go.mod
go.sum
internal/wrappers/results-http.go

> Increase page limit to 10,000 in results service requests
> https://checkmarx.atlassian.net/browse/AST-77955
> X

CLI | Increase page limit to 10,000 in results service requests (AST-77955)

---

internal/commands/scan.go

> https://checkmarx.atlassian.net/browse/AST-42950
>

Ensure proper cleanup of temporary ZIP files (AST-42950)

---

gonMac.hcl

Change gonMac.hcl signing user

---

.github/workflows/ci.yml

> https://checkmarx.atlassian.net/browse/AST-77702
>

Update artifact actions to v4 (AST-77702)

---

.github/workflows/release.yml

Add new notify step in release pipeline (AST-000)

---

.github/workflows/release.yml

Daniel check action (AST-000)

---

.github/workflows/release.yml

Wait for build to finish (AST-000)

---

.github/workflows/release.yml

update set up docker version

---

.github/workflows/release.yml

Fix notify job (AST-000)

---

internal/commands/result.go

> Change RuleID feild in sarif report to be more informative
> https://checkmarx.atlassian.net/browse/AST-77145
> X

CLI | Change Rule ID in Sarif files (AST-77145)

---

.github/workflows/release.yml

CLI | Add Jira product name to release pipeline (AST-0000)

---

.github/workflows/ai-code-review.yml

Add AI code review action (AST-000)

---

internal/commands/predicates.go

Change descreiption of custom states help guide (AST-80216)

---

.github/workflows/ci.yml
internal/commands/result.go

Fix sonar column start position (AST-65811)

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/ci.yml
.github/workflows/release.yml
go.mod
internal/commands/root.go
internal/params/binds.go
internal/params/envs.go
internal/params/flags.go
internal/params/keys.go
internal/wrappers/client.go
internal/wrappers/client_test.go
test/integration/scan_test.go

Add origin to all outbound calls (AST-000)

---

internal/commands/scarealtime/sca-realtime.go

> https://checkmarx.atlassian.net/browse/AST-83951
>

Change sca real time chunks from 50 to 20 (AST-83951)

---

internal/commands/scan.go

Add critical severity to kics realtime allowed exit codes (AST-000)

---

internal/commands/root.go
internal/commands/util/usercount/user-count.go
internal/params/flags.go
test/integration/pr_test.go

https://checkmarx.atlassian.net/browse/AST-87103

Remove-profile-flag-becuase-lack-support (AST-87103)

---

.github/workflows/ci.yml
.pre-commit-config.yaml
test/integration/pre_commit_test.go

Add integration test for pre-commit flag (AST-89008)

---

cmd/main.go
internal/commands/policymanagement/policy.go
internal/constants/feature-flags/feature-flags.go
internal/wrappers/policy-http.go
test/integration/util_command.go

https://checkmarx.atlassian.net/browse/AST-88767

CLI | Ignore Policy Management 401 response code (AST-88767)

---

.pre-commit-config.yaml
internal/commands/result.go
internal/commands/result_test.go
internal/wrappers/export.go
internal/wrappers/results-sca-package.go

Add dev and test dependency flags to SCA results 
https://checkmarx.atlassian.net/browse/AST-80203

Add dev and test dependency flags to SCA results (AST-80203)

---

internal/commands/result.go
internal/commands/result_test.go
internal/wrappers/feature-flags.go

Add RISK_MANAGEMENT_IDES_PROJECT_RESULTS_SCORES_API_ENABLED FF

Add FF To ASPM (AST-89323)

---

internal/wrappers/feature-flags-http.go

https://checkmarx.atlassian.net/browse/AST-86767

Return error for 500 errors from server (AST-86767)

---

internal/wrappers/results-json.go
test/integration/util_command.go

For ASPM feature.
https://checkmarx.atlassian.net/browse/AST-94451

Add an AlternateID field to enable opening the vulnerability details.

---

internal/commands/root.go
test/integration/result_test.go

Add support for uppercase filter in results command (AST-95864)

---

internal/wrappers/client.go
internal/wrappers/client_test.go

*Implement retry logic for handling 5XX server responses*
*[Fix bug number AST-95350](https://checkmarx.atlassian.net/browse/AST-95350)*
*[Fix bug number AST-89866](https://checkmarx.atlassian.net/browse/AST-89866)*

Implement retry logic for token-related 5XX responses (AST-95350) , (AST-89866)

---

go.mod
go.sum
internal/services/ossrealtime/oss-realtime.go

Update manifest-parser to v0.0.5 and fix FilePath casing

---

go.mod
go.sum
internal/services/ossrealtime/oss-realtime.go

Update manifest parser to v0.0.6 (AST-0000)

---

internal/commands/oss-realtime-engine.go
internal/constants/errors/errors.go
internal/services/ossrealtime/oss-realtime.go
test/integration/data/manifests/no_dep_packageJson/package.json
test/integration/oss-realtime_test.go

Enahance errors in oss realtime (AST-99446)

---

internal/commands/scan.go
internal/commands/util/remediation.go

Update kics version from 2.1.9 to 2.1.10 (AST-99805)

---

Dockerfile
go.mod
go.sum

*Fix found vulnerabilities on trivy*

Fix found vulnerabilities on trivy

---

internal/params/filters.go

*Added Directory.Build.props package manager to support SCA scan.*

AddedDirectoryBuildPropsPackageManager (AST-99980)

---

internal/wrappers/results-summary.go

*Fix issue of Scan Summary shows -1 as the result count even though the Container Security engine did not run for markdown report type*
*[Link any related issues or tickets.](https://checkmarx.atlassian.net/browse/AST-101835)*

Fix bug number (AST-101835)

---

internal/commands/scan.go
internal/commands/util/remediation.go

Update kics version from 2.1.10 to 2.1.11 (AST-104154)

---

internal/services/realtimeengine/secretsrealtime/config.go
internal/services/realtimeengine/secretsrealtime/secrets-realtime.go
internal/services/realtimeengine/secretsrealtime/secrets-realtime_test.go

Change ignore flow in Secrets real time by SecretValue (AST-00000)

---

internal/wrappers/results-json.go
test/integration/result_test.go

*Included 'publishedAt'  in JSON Results*

Added publishedAt field in json report(AST-87044)

---

go.mod
internal/wrappers/access-management.go

Update payload of assignment response (AST-109354)

---

internal/commands/scan.go
internal/commands/util/remediation.go

Update kics version from 2.1.11 to 2.1.13 (AST-109562)

---

internal/services/realtimeengine/iacrealtime/constants.go
internal/services/realtimeengine/iacrealtime/mapper.go

Filter IAC info severity results (AST-0000)

---

go.mod
go.sum
internal/services/realtimeengine/secretsrealtime/config.go
internal/services/realtimeengine/secretsrealtime/secrets-realtime.go
internal/services/realtimeengine/secretsrealtime/secrets-realtime_test.go

Remove file path from secrets ignore flow (AST-00000)
